// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/outbox_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/outbox_repository.go -destination=internal/mocks/mock_outbox_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/cypherlabdev/order-book-service/internal/models"
	uuid "github.com/google/uuid"
	v5 "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// CleanupProcessedEvents mocks base method.
func (m *MockOutboxRepository) CleanupProcessedEvents(ctx context.Context, olderThan time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupProcessedEvents", ctx, olderThan)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupProcessedEvents indicates an expected call of CleanupProcessedEvents.
func (mr *MockOutboxRepositoryMockRecorder) CleanupProcessedEvents(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupProcessedEvents", reflect.TypeOf((*MockOutboxRepository)(nil).CleanupProcessedEvents), ctx, olderThan)
}

// Create mocks base method.
func (m *MockOutboxRepository) Create(ctx context.Context, tx v5.Tx, event *models.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboxRepositoryMockRecorder) Create(ctx, tx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboxRepository)(nil).Create), ctx, tx, event)
}

// GetUnprocessedEvents mocks base method.
func (m *MockOutboxRepository) GetUnprocessedEvents(ctx context.Context, limit int) ([]*models.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnprocessedEvents", ctx, limit)
	ret0, _ := ret[0].([]*models.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnprocessedEvents indicates an expected call of GetUnprocessedEvents.
func (mr *MockOutboxRepositoryMockRecorder) GetUnprocessedEvents(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnprocessedEvents", reflect.TypeOf((*MockOutboxRepository)(nil).GetUnprocessedEvents), ctx, limit)
}

// IncrementRetryCount mocks base method.
func (m *MockOutboxRepository) IncrementRetryCount(ctx context.Context, eventID uuid.UUID, errorMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRetryCount", ctx, eventID, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRetryCount indicates an expected call of IncrementRetryCount.
func (mr *MockOutboxRepositoryMockRecorder) IncrementRetryCount(ctx, eventID, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRetryCount", reflect.TypeOf((*MockOutboxRepository)(nil).IncrementRetryCount), ctx, eventID, errorMsg)
}

// MarkProcessed mocks base method.
func (m *MockOutboxRepository) MarkProcessed(ctx context.Context, eventID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessed", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessed indicates an expected call of MarkProcessed.
func (mr *MockOutboxRepositoryMockRecorder) MarkProcessed(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkProcessed), ctx, eventID)
}
