// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/order_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/order_repository.go -destination=internal/mocks/mock_order_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/cypherlabdev/order-book-service/internal/models"
	uuid "github.com/google/uuid"
	v5 "github.com/jackc/pgx/v5"
	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockOrderRepository) Cancel(ctx context.Context, tx v5.Tx, id uuid.UUID, sagaID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, tx, id, sagaID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockOrderRepositoryMockRecorder) Cancel(ctx, tx, id, sagaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockOrderRepository)(nil).Cancel), ctx, tx, id, sagaID)
}

// Create mocks base method.
func (m *MockOrderRepository) Create(ctx context.Context, tx v5.Tx, order *models.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepositoryMockRecorder) Create(ctx, tx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepository)(nil).Create), ctx, tx, order)
}

// GetByID mocks base method.
func (m *MockOrderRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrderRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrderRepository)(nil).GetByID), ctx, id)
}

// GetByIDForUpdate mocks base method.
func (m *MockOrderRepository) GetByIDForUpdate(ctx context.Context, tx v5.Tx, id uuid.UUID) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDForUpdate", ctx, tx, id)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDForUpdate indicates an expected call of GetByIDForUpdate.
func (mr *MockOrderRepositoryMockRecorder) GetByIDForUpdate(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDForUpdate", reflect.TypeOf((*MockOrderRepository)(nil).GetByIDForUpdate), ctx, tx, id)
}

// GetByMarketAndSelection mocks base method.
func (m *MockOrderRepository) GetByMarketAndSelection(ctx context.Context, marketID, selectionID string, side models.OrderSide, status models.OrderStatus, limit int) ([]*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMarketAndSelection", ctx, marketID, selectionID, side, status, limit)
	ret0, _ := ret[0].([]*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMarketAndSelection indicates an expected call of GetByMarketAndSelection.
func (mr *MockOrderRepositoryMockRecorder) GetByMarketAndSelection(ctx, marketID, selectionID, side, status, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMarketAndSelection", reflect.TypeOf((*MockOrderRepository)(nil).GetByMarketAndSelection), ctx, marketID, selectionID, side, status, limit)
}

// GetBySagaID mocks base method.
func (m *MockOrderRepository) GetBySagaID(ctx context.Context, sagaID string) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySagaID", ctx, sagaID)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySagaID indicates an expected call of GetBySagaID.
func (mr *MockOrderRepositoryMockRecorder) GetBySagaID(ctx, sagaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySagaID", reflect.TypeOf((*MockOrderRepository)(nil).GetBySagaID), ctx, sagaID)
}

// GetByUserID mocks base method.
func (m *MockOrderRepository) GetByUserID(ctx context.Context, userID uuid.UUID, limit, offset int) ([]*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockOrderRepositoryMockRecorder) GetByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockOrderRepository)(nil).GetByUserID), ctx, userID, limit, offset)
}

// GetPendingOrders mocks base method.
func (m *MockOrderRepository) GetPendingOrders(ctx context.Context, marketID string) ([]*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingOrders", ctx, marketID)
	ret0, _ := ret[0].([]*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingOrders indicates an expected call of GetPendingOrders.
func (mr *MockOrderRepositoryMockRecorder) GetPendingOrders(ctx, marketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingOrders", reflect.TypeOf((*MockOrderRepository)(nil).GetPendingOrders), ctx, marketID)
}

// Settle mocks base method.
func (m *MockOrderRepository) Settle(ctx context.Context, tx v5.Tx, id uuid.UUID, result string, actualPayout decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Settle", ctx, tx, id, result, actualPayout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Settle indicates an expected call of Settle.
func (mr *MockOrderRepositoryMockRecorder) Settle(ctx, tx, id, result, actualPayout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Settle", reflect.TypeOf((*MockOrderRepository)(nil).Settle), ctx, tx, id, result, actualPayout)
}

// Update mocks base method.
func (m *MockOrderRepository) Update(ctx context.Context, tx v5.Tx, order *models.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrderRepositoryMockRecorder) Update(ctx, tx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrderRepository)(nil).Update), ctx, tx, order)
}

// UpdateMatched mocks base method.
func (m *MockOrderRepository) UpdateMatched(ctx context.Context, tx v5.Tx, id uuid.UUID, sizeMatched, sizeRemaining decimal.Decimal, status models.OrderStatus, version int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMatched", ctx, tx, id, sizeMatched, sizeRemaining, status, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMatched indicates an expected call of UpdateMatched.
func (mr *MockOrderRepositoryMockRecorder) UpdateMatched(ctx, tx, id, sizeMatched, sizeRemaining, status, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMatched", reflect.TypeOf((*MockOrderRepository)(nil).UpdateMatched), ctx, tx, id, sizeMatched, sizeRemaining, status, version)
}
