// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/idempotency_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/idempotency_repository.go -destination=internal/mocks/mock_idempotency_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"
	time "time"

	v5 "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockIdempotencyRepository is a mock of IdempotencyRepository interface.
type MockIdempotencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyRepositoryMockRecorder
	isgomock struct{}
}

// MockIdempotencyRepositoryMockRecorder is the mock recorder for MockIdempotencyRepository.
type MockIdempotencyRepositoryMockRecorder struct {
	mock *MockIdempotencyRepository
}

// NewMockIdempotencyRepository creates a new mock instance.
func NewMockIdempotencyRepository(ctrl *gomock.Controller) *MockIdempotencyRepository {
	mock := &MockIdempotencyRepository{ctrl: ctrl}
	mock.recorder = &MockIdempotencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyRepository) EXPECT() *MockIdempotencyRepositoryMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockIdempotencyRepository) Check(ctx context.Context, key, requestHash string) (json.RawMessage, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, key, requestHash)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Check indicates an expected call of Check.
func (mr *MockIdempotencyRepositoryMockRecorder) Check(ctx, key, requestHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockIdempotencyRepository)(nil).Check), ctx, key, requestHash)
}

// CleanupExpired mocks base method.
func (m *MockIdempotencyRepository) CleanupExpired(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpired", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpired indicates an expected call of CleanupExpired.
func (mr *MockIdempotencyRepositoryMockRecorder) CleanupExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpired", reflect.TypeOf((*MockIdempotencyRepository)(nil).CleanupExpired), ctx)
}

// Store mocks base method.
func (m *MockIdempotencyRepository) Store(ctx context.Context, key, requestHash string, responseData any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, key, requestHash, responseData, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockIdempotencyRepositoryMockRecorder) Store(ctx, key, requestHash, responseData, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockIdempotencyRepository)(nil).Store), ctx, key, requestHash, responseData, ttl)
}

// StoreInTransaction mocks base method.
func (m *MockIdempotencyRepository) StoreInTransaction(ctx context.Context, tx v5.Tx, key, requestHash string, responseData any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreInTransaction", ctx, tx, key, requestHash, responseData, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreInTransaction indicates an expected call of StoreInTransaction.
func (mr *MockIdempotencyRepositoryMockRecorder) StoreInTransaction(ctx, tx, key, requestHash, responseData, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreInTransaction", reflect.TypeOf((*MockIdempotencyRepository)(nil).StoreInTransaction), ctx, tx, key, requestHash, responseData, ttl)
}
